import JSZip from 'jszip'
import type { RateSheet, Region } from '../../types/gacha/rateSheet'
import type { AuditTrail } from '../../types/gacha/audit'
import { blockFilename } from './generateAuditJson'
import type { RenderedBlock } from './renderTemplate'

export interface ExportOptions {
  includeHtml: boolean
  includePng: boolean
  includeJson: boolean
}

export interface ExportResult {
  blob: Blob
  filename: string
  formats: string[]
}

export interface ExportInputs {
  rateSheet: RateSheet
  regions: Region[]
  blocks: RenderedBlock[]
  pngBlobByKey?: Map<string, Blob>
  auditTrail: AuditTrail
  options: ExportOptions
}

export async function exportZip(inputs: ExportInputs): Promise<ExportResult> {
  const { rateSheet, regions, blocks, pngBlobByKey, auditTrail, options } = inputs
  const zip = new JSZip()
  const formats: string[] = []

  if (options.includeHtml) {
    formats.push('html')
    for (const block of blocks) {
      zip.file(blockFilename(block.region, block.pool_id, 'html'), block.html)
    }
  }

  if (options.includePng && pngBlobByKey) {
    formats.push('png')
    for (const block of blocks) {
      const blob = pngBlobByKey.get(`${block.region}:${block.pool_id}`)
      if (!blob) continue
      zip.file(blockFilename(block.region, block.pool_id, 'png'), blob)
    }
  }

  if (options.includeJson) {
    formats.push('json')
    zip.file('audit-trail.json', JSON.stringify(auditTrail, null, 2))
  }

  zip.file('README.txt', buildReadme(rateSheet, regions, auditTrail))

  const blob = await zip.generateAsync({ type: 'blob' })
  const dateStamp = new Date().toISOString().split('T')[0]
  const slug = slugifyGameName(rateSheet.metadata.game_name_en, rateSheet.metadata.game_id)
  return {
    blob,
    filename: `gacha-disclosure-${slug}-${dateStamp}.zip`,
    formats,
  }
}

export function slugifyGameName(name: string, fallback: string): string {
  const fromName = slugify(name)
  if (fromName) return fromName
  const fromFallback = slugify(fallback)
  return fromFallback || 'game'
}

function slugify(input: string): string {
  return input.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_-]+/g, '')
}

function buildReadme(rateSheet: RateSheet, regions: Region[], audit: AuditTrail): string {
  const lines = [
    'Qyren Gacha Disclosure Pack',
    '',
    `Game: ${rateSheet.metadata.game_name_en || rateSheet.metadata.game_id}`,
    `Studio: ${rateSheet.metadata.studio_name}`,
    `Generated: ${audit.generated_at}`,
    `Tool version: ${audit.tool_version}`,
    `Rate sheet hash: ${audit.rate_sheet_hash}`,
    '',
    `Regions: ${regions.join(', ')}`,
    '',
    'Files (SHA-256 of file bytes — verify with sha256sum):',
    ...audit.generated_blocks.map(
      (b) => `  ${b.block_uri} (${b.format}, ${b.block_hash})`,
    ),
    '  audit-trail.json (full audit record)',
    '',
    'Disclaimer:',
    '  This pack was generated by Qyren Gacha Disclosure Pack. The audit attests',
    '  to what was provided and generated, not to legal compliance. The studio is',
    '  responsible for compliance review before publication.',
    '',
    'Source: https://github.com/rknlabs/qyren-tools',
  ]
  return lines.join('\n')
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
