import JSZip from 'jszip'
import type { RateSheet, Region } from '../../types/gacha/rateSheet'
import type { AuditTrail } from '../../types/gacha/audit'
import { blockFilename } from './generateAuditJson'
import type { RenderedBlock } from './renderTemplate'
import { renderHtmlToPng } from './renderPng'

export interface ExportOptions {
  includeHtml: boolean
  includePng: boolean
  includeJson: boolean
}

export interface ExportResult {
  blob: Blob
  filename: string
  formats: string[]
}

export async function exportZip(
  rateSheet: RateSheet,
  regions: Region[],
  blocks: RenderedBlock[],
  auditTrail: AuditTrail,
  options: ExportOptions,
): Promise<ExportResult> {
  const zip = new JSZip()
  const formats: string[] = []

  if (options.includeHtml) {
    formats.push('html')
    for (const block of blocks) {
      zip.file(blockFilename(block.region, block.pool_id, 'html'), block.html)
    }
  }

  if (options.includePng) {
    formats.push('png')
    for (const block of blocks) {
      try {
        const png = await renderHtmlToPng(block.html)
        zip.file(blockFilename(block.region, block.pool_id, 'png'), png)
      } catch (err) {
        console.error(`PNG render failed for ${block.region}:${block.pool_id}`, err)
      }
    }
  }

  if (options.includeJson) {
    formats.push('json')
    zip.file('audit-trail.json', JSON.stringify(auditTrail, null, 2))
  }

  zip.file('README.txt', buildReadme(rateSheet, regions, auditTrail))

  const blob = await zip.generateAsync({ type: 'blob' })
  const dateStamp = new Date().toISOString().split('T')[0]
  const safeGameId = rateSheet.metadata.game_id.replace(/[^a-zA-Z0-9_-]+/g, '-') || 'game'
  return {
    blob,
    filename: `gacha-disclosure-${safeGameId}-${dateStamp}.zip`,
    formats,
  }
}

function buildReadme(rateSheet: RateSheet, regions: Region[], audit: AuditTrail): string {
  const lines = [
    'Qyren Gacha Disclosure Pack',
    '',
    `Game: ${rateSheet.metadata.game_name_en || rateSheet.metadata.game_id}`,
    `Studio: ${rateSheet.metadata.studio_name}`,
    `Generated: ${audit.generated_at}`,
    `Tool version: ${audit.tool_version}`,
    `Rate sheet hash: ${audit.rate_sheet_hash}`,
    '',
    `Regions: ${regions.join(', ')}`,
    '',
    'Files:',
    ...audit.generated_blocks.map(
      (b) => `  ${b.block_uri} (${b.format}, hash: ${b.block_hash})`,
    ),
    '  audit-trail.json (full audit record)',
    '',
    'Disclaimer:',
    '  This pack was generated by Qyren Gacha Disclosure Pack. The audit attests',
    '  to what was provided and generated, not to legal compliance. The studio is',
    '  responsible for compliance review before publication.',
    '',
    'Source: https://github.com/rknlabs/qyren-tools',
  ]
  return lines.join('\n')
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
