import type { RateSheet, Region } from '../../types/gacha/rateSheet'
import type { ValidationResult } from '../../types/gacha/validation'
import type { AuditTrail, GeneratedBlock } from '../../types/gacha/audit'
import { canonicalizeJson, sha256 } from './hash'
import type { RenderedBlock } from './renderTemplate'

const DISCLAIMER =
  'This audit was generated by Qyren Gacha Disclosure Pack. The audit attests to what the studio provided and what was generated, not to legal compliance. The studio is responsible for compliance review before publication.'

export interface AuditInputs {
  rateSheet: RateSheet
  regions: Region[]
  validationResults: ValidationResult[]
  blocks: RenderedBlock[]
  // Hash maps keyed by `${region}:${pool_id}`. Each entry is a SHA-256 of the
  // exact bytes that get written into the ZIP, so a regulator running
  // sha256sum on the file gets the same value as the audit reports.
  htmlHashByKey: Map<string, string>
  pngHashByKey?: Map<string, string>
  toolVersion: string
  includeHtml: boolean
  includePng: boolean
}

export async function generateAuditTrail(inputs: AuditInputs): Promise<AuditTrail> {
  const rateSheetHash = await sha256(canonicalizeJson(inputs.rateSheet))
  const generated: GeneratedBlock[] = []
  for (const block of inputs.blocks) {
    const key = `${block.region}:${block.pool_id}`
    if (inputs.includeHtml) {
      const hash = inputs.htmlHashByKey.get(key) ?? ''
      generated.push({
        region: block.region,
        format: 'html',
        block_hash: hash,
        block_uri: blockFilename(block.region, block.pool_id, 'html'),
      })
    }
    if (inputs.includePng) {
      const hash = inputs.pngHashByKey?.get(key) ?? ''
      generated.push({
        region: block.region,
        format: 'png',
        block_hash: hash,
        block_uri: blockFilename(block.region, block.pool_id, 'png'),
      })
    }
  }

  return {
    schema_version: '1.0',
    generated_at: new Date().toISOString(),
    tool_version: inputs.toolVersion,
    rate_sheet_hash: rateSheetHash,
    rate_sheet_metadata: inputs.rateSheet.metadata,
    regions_targeted: inputs.regions,
    validation_results: inputs.validationResults,
    generated_blocks: generated,
    disclaimer: DISCLAIMER,
  }
}

export function blockFilename(region: Region, poolId: string, ext: 'html' | 'png'): string {
  const safePool = poolId.replace(/[^a-zA-Z0-9_-]+/g, '-')
  return `disclosure-${region.toLowerCase()}-${safePool}.${ext}`
}
